// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package models

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, name, email, created_at FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, db DBTX, id int32) (User, error) {
	row := db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
